"""Add analyzer data models (Counting, Parking, Crowd, ODOL)

Revision ID: 15a2ca727881
Revises: 2bcaf4ad3b08
Create Date: 2025-11-24 10:22:34.172644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a2ca727881'
down_revision = '2bcaf4ad3b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counting_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('counts_jauh_car', sa.Integer(), nullable=True),
    sa.Column('counts_jauh_motorcycle', sa.Integer(), nullable=True),
    sa.Column('counts_jauh_bus', sa.Integer(), nullable=True),
    sa.Column('counts_jauh_truck', sa.Integer(), nullable=True),
    sa.Column('counts_dekat_car', sa.Integer(), nullable=True),
    sa.Column('counts_dekat_motorcycle', sa.Integer(), nullable=True),
    sa.Column('counts_dekat_bus', sa.Integer(), nullable=True),
    sa.Column('counts_dekat_truck', sa.Integer(), nullable=True),
    sa.Column('grand_total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('counting_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counting_data_location'), ['location'], unique=False)

    op.create_table('crowd_detections',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('crowd_size', sa.Integer(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crowd_detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crowd_detections_location'), ['location'], unique=False)

    op.create_table('odol_detections',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('aspect_ratio', sa.Float(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('odol_detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_odol_detections_location'), ['location'], unique=False)

    op.create_table('parking_violations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('parked_duration_sec', sa.Float(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parking_violations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parking_violations_location'), ['location'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_violations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parking_violations_location'))

    op.drop_table('parking_violations')
    with op.batch_alter_table('odol_detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_odol_detections_location'))

    op.drop_table('odol_detections')
    with op.batch_alter_table('crowd_detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crowd_detections_location'))

    op.drop_table('crowd_detections')
    with op.batch_alter_table('counting_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counting_data_location'))

    op.drop_table('counting_data')
    # ### end Alembic commands ###
