"""Menghapus kolom icon dari tabel kontak

Revision ID: 520e70ee9c54
Revises: 802c0dbc2ff5
Create Date: 2025-11-11 13:20:01.022341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520e70ee9c54'
down_revision = '802c0dbc2ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kontak', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kontak', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
