"""Initial schema

Revision ID: 802c0dbc2ff5
Revises: 
Create Date: 2025-11-09 20:41:52.941739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802c0dbc2ff5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batas_wilayah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('jenis', sa.String(length=50), nullable=False),
    sa.Column('geojson', sa.Text(), nullable=True),
    sa.Column('keterangan', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batas_wilayah', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batas_wilayah_jenis'), ['jenis'], unique=False)

    op.create_table('cctv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lokasi', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('camera_type', sa.String(length=100), nullable=True),
    sa.Column('stream_url', sa.String(length=500), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kontak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instansi', sa.String(length=100), nullable=False),
    sa.Column('nomor_telp', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.Column('reset_token_expiration', sa.DateTime(), nullable=True),
    sa.Column('otp_secret', sa.String(length=6), nullable=True),
    sa.Column('otp_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('reset_token'),
    sa.UniqueConstraint('username')
    )
    op.create_table('dispatch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kontak_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('tipe_dispatch', sa.String(length=50), nullable=False),
    sa.Column('instruksi', sa.Text(), nullable=False),
    sa.Column('waktu_kirim', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['kontak_id'], ['kontak.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispatch')
    op.drop_table('users')
    op.drop_table('kontak')
    op.drop_table('cctv')
    with op.batch_alter_table('batas_wilayah', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batas_wilayah_jenis'))

    op.drop_table('batas_wilayah')
    # ### end Alembic commands ###
